# Generated by Django 5.0.1 on 2026-03-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã huỷ'), ('RETURNED', 'Đã trả')], default='PENDING', max_length=10),
        ),
    ]
