# Generated by Django 5.0.1 on 2026-03-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
